# Stage 1: Build project
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Build project
RUN npm run build

# Stage 2: Final image
FROM node:18-alpine AS runner

WORKDIR /app

# Copy phần cần thiết
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next

# Copy luôn .env vào image
COPY .env ./

EXPOSE 3000

ENV NODE_ENV=production

CMD ["npm", "run", "start"]
